// Global using directives

global using Clean_Architecture_Template_Application_Layer.Implementations;
global using Clean_Architecture_Template_Domain_Layer.Abstraction;
global using FluentAssertions;