services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DatabaseConnectionString=Server=sqlserver;Database=CleanArchitectureTemplateDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True

volumes:
  sqlserver_data: 